services:
  backend:
    build: ./stock-crawler
    ports:
      - "8000:8000"
    container_name: stock-backend
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}   # ← 加這行

  frontend:
    build: ./stock-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    container_name: stock-frontend
    environment:
      - VITE_BACKEND_URL=http://backend:8000   # ← 加這行